name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your AWS region

    - name: Upload Dockerrun.aws.json to Elastic Beanstalk
      run: |
        aws elasticbeanstalk update-environment \
          --environment-name Testfrontend-application-env \
          --version-label testfrontend-application-version-3 \
          --application-name testfrontend-application \
          --option-settings file://Dockerrun.aws.json
