name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build --tag ${{ secrets.DOCKER_USERNAME }}/testfrontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/testfrontend:latest

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1  # Change this to your AWS region
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name testfrontend-application \
          --version-label v1.0.0 \
          --source-bundle S3Bucket="elasticbeanstalk-ap-south-1-024848475699",S3Key="testfrontend-28605066fe6ac0dc2476e324267e0c23be01a682.zip"
        aws elasticbeanstalk update-environment \
          --environment-name Testfrontend-application-env \
          --version-label v1.0.0

    - name: Notify deployment
      run: echo "Deployment to AWS Elastic Beanstalk completed successfully."
